version: '3.8'
services:
  backend:
    build: ./backend
    container_name: expense-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/expensetracker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: expense-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: expense-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=expensetracker
    ports:
      - "3306:3306"
